-- Smazani tabulek
DROP TABLE PRODUCTS,
USERS,
ORDERS;

-- Vytvoření tabulky 'products'
CREATE TABLE PRODUCTS (
	PRODUCT_ID SERIAL PRIMARY KEY,
	PRODUCT_NAME VARCHAR(255) NOT NULL,
	PRICE DECIMAL(10, 2) NOT NULL,
	COST DECIMAL(10, 2) NOT NULL
);

-- Vytvoření tabulky 'users'
CREATE TABLE USERS (
	USER_ID SERIAL PRIMARY KEY,
	USER_NAME VARCHAR(255) NOT NULL
);

-- Vytvoření tabulky 'orders'
CREATE TABLE ORDERS (
	ORDER_ID SERIAL PRIMARY KEY,
	USER_ID INT,
	PRODUCT_ID INT,
	QUANTITY INT,
	ORDER_DATE DATE,
	FOREIGN KEY (USER_ID) REFERENCES USERS (USER_ID),
	FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS (PRODUCT_ID)
);